/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomToken = IDL.Record({
  'decimals' : IDL.Nat8,
  'ledgerCanisterId' : IDL.Text,
  'indexCanisterId' : IDL.Opt(IDL.Text),
  'addedAt' : IDL.Int,
  'symbol' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const WalletLabel = IDL.Record({
  'address' : IDL.Text,
  'walletLabel' : IDL.Text,
});
export const Favorite = IDL.Record({
  'address' : IDL.Text,
  'pinnedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addCustomToken' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat8],
      [CustomToken],
      [],
    ),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAllLabels' : IDL.Func([], [IDL.Vec(WalletLabel)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
  'getLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'listCustomTokens' : IDL.Func([], [IDL.Vec(CustomToken)], ['query']),
  'ping' : IDL.Func([], [IDL.Record({ 'status' : IDL.Text })], ['query']),
  'removeCustomToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'removeLabel' : IDL.Func([IDL.Text], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setLabel' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomToken = IDL.Record({
    'decimals' : IDL.Nat8,
    'ledgerCanisterId' : IDL.Text,
    'indexCanisterId' : IDL.Opt(IDL.Text),
    'addedAt' : IDL.Int,
    'symbol' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const WalletLabel = IDL.Record({
    'address' : IDL.Text,
    'walletLabel' : IDL.Text,
  });
  const Favorite = IDL.Record({ 'address' : IDL.Text, 'pinnedAt' : IDL.Int });
  
  return IDL.Service({
    'addCustomToken' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat8],
        [CustomToken],
        [],
      ),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAllLabels' : IDL.Func([], [IDL.Vec(WalletLabel)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
    'getLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'listCustomTokens' : IDL.Func([], [IDL.Vec(CustomToken)], ['query']),
    'ping' : IDL.Func([], [IDL.Record({ 'status' : IDL.Text })], ['query']),
    'removeCustomToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'removeLabel' : IDL.Func([IDL.Text], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setLabel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };