/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface CustomToken {
  'decimals' : number,
  'ledgerCanisterId' : string,
  'indexCanisterId' : [] | [string],
  'addedAt' : bigint,
  'symbol' : string,
}
export interface Favorite { 'address' : string, 'pinnedAt' : bigint }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WalletLabel { 'address' : string, 'walletLabel' : string }
export interface _SERVICE {
  /**
   * / Add or upsert a custom token for the calling user, deduplicated by ledger canister ID.
   */
  'addCustomToken' : ActorMethod<
    [string, [] | [string], string, number],
    CustomToken
  >,
  /**
   * / Add or update a wallet as a favorite for the calling user.
   */
  'addFavorite' : ActorMethod<[string], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Get all wallet labels for the calling user.
   */
  'getAllLabels' : ActorMethod<[], Array<WalletLabel>>,
  /**
   * / Static Markdown documentation of this canister's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Get all favorite wallets for the calling user.
   */
  'getFavorites' : ActorMethod<[], Array<Favorite>>,
  /**
   * / Get the label for a specific wallet address, or null if not set.
   */
  'getLabel' : ActorMethod<[string], [] | [string]>,
  /**
   * / Get all custom tokens tracked by the calling user.
   */
  'listCustomTokens' : ActorMethod<[], Array<CustomToken>>,
  'ping' : ActorMethod<[], { 'status' : string }>,
  /**
   * / Remove a custom token by ledger canister ID. Returns true when an entry was removed.
   */
  'removeCustomToken' : ActorMethod<[string], boolean>,
  /**
   * / Remove a wallet from the calling user's favorites.
   */
  'removeFavorite' : ActorMethod<[string], undefined>,
  /**
   * / Remove the label for a specific wallet address.
   */
  'removeLabel' : ActorMethod<[string], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Set or overwrite a wallet label for the calling user. Label is max 6 chars.
   */
  'setLabel' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];