/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Favorite { 'address' : string, 'pinnedAt' : bigint }
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface WalletLabel { 'address' : string, 'walletLabel' : string }
export interface _SERVICE {
  'addFavorite' : ActorMethod<[string], undefined>,
  'getAllLabels' : ActorMethod<[], Array<WalletLabel>>,
  'getFavorites' : ActorMethod<[], Array<Favorite>>,
  'getLabel' : ActorMethod<[string], [] | [string]>,
  'icexplorer_portfolio' : ActorMethod<[string], string>,
  'icexplorer_transform' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpRequestResult }],
    HttpRequestResult
  >,
  'icexplorer_txlist' : ActorMethod<[string], string>,
  'ping' : ActorMethod<[], { 'status' : string }>,
  'removeFavorite' : ActorMethod<[string], undefined>,
  'removeLabel' : ActorMethod<[string], undefined>,
  'setLabel' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];