/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WalletLabel = IDL.Record({
  'address' : IDL.Text,
  'walletLabel' : IDL.Text,
});
export const Favorite = IDL.Record({
  'address' : IDL.Text,
  'pinnedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'getAllLabels' : IDL.Func([], [IDL.Vec(WalletLabel)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
  'getLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'ping' : IDL.Func([], [IDL.Record({ 'status' : IDL.Text })], ['query']),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'removeLabel' : IDL.Func([IDL.Text], [], []),
  'setLabel' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WalletLabel = IDL.Record({
    'address' : IDL.Text,
    'walletLabel' : IDL.Text,
  });
  const Favorite = IDL.Record({ 'address' : IDL.Text, 'pinnedAt' : IDL.Int });
  
  return IDL.Service({
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'getAllLabels' : IDL.Func([], [IDL.Vec(WalletLabel)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
    'getLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'ping' : IDL.Func([], [IDL.Record({ 'status' : IDL.Text })], ['query']),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'removeLabel' : IDL.Func([IDL.Text], [], []),
    'setLabel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };