/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface CustomToken {
    decimals: number;
    ledgerCanisterId: string;
    indexCanisterId?: string;
    addedAt: bigint;
    symbol: string;
}
export interface Favorite {
    address: string;
    pinnedAt: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface WalletLabel {
    address: string;
    walletLabel: string;
}
export interface backendInterface {
    /**
     * / Add or upsert a custom token for the calling user, deduplicated by ledger canister ID.
     */
    addCustomToken(ledgerCanisterId: string, indexCanisterId: string | null, symbol_: string, decimals: number): Promise<CustomToken>;
    /**
     * / Add or update a wallet as a favorite for the calling user.
     */
    addFavorite(address: string): Promise<void>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Get all wallet labels for the calling user.
     */
    getAllLabels(): Promise<Array<WalletLabel>>;
    /**
     * / Static Markdown documentation of this canister's public API.
     */
    getApiDoc(): Promise<string>;
    /**
     * / Get all favorite wallets for the calling user.
     */
    getFavorites(): Promise<Array<Favorite>>;
    /**
     * / Get the label for a specific wallet address, or null if not set.
     */
    getLabel(address: string): Promise<string | null>;
    /**
     * / Get all custom tokens tracked by the calling user.
     */
    listCustomTokens(): Promise<Array<CustomToken>>;
    ping(): Promise<{
        status: string;
    }>;
    /**
     * / Remove a custom token by ledger canister ID. Returns true when an entry was removed.
     */
    removeCustomToken(ledgerCanisterId: string): Promise<boolean>;
    /**
     * / Remove a wallet from the calling user's favorites.
     */
    removeFavorite(address: string): Promise<void>;
    /**
     * / Remove the label for a specific wallet address.
     */
    removeLabel(address: string): Promise<void>;
    schema(): Promise<string>;
    /**
     * / Set or overwrite a wallet label for the calling user. Label is max 6 chars.
     */
    setLabel(address: string, lbl: string): Promise<void>;
}
import type { Cell as _Cell, CustomToken as _CustomToken, Result as _Result, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomToken(arg0: string, arg1: string | null, arg2: string, arg3: number): Promise<CustomToken> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomToken(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_CustomToken_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomToken(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_CustomToken_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLabels(): Promise<Array<WalletLabel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabels();
            return result;
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getFavorites(): Promise<Array<Favorite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getLabel(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabel(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabel(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCustomTokens(): Promise<Array<CustomToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomTokens();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomTokens();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async ping(): Promise<{
        status: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.ping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ping();
            return result;
        }
    }
    async removeCustomToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCustomToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCustomToken(arg0);
            return result;
        }
    }
    async removeFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async removeLabel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLabel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLabel(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setLabel(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLabel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLabel(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Cell_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CustomToken_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomToken): CustomToken {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n11(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decimals: number;
    ledgerCanisterId: string;
    indexCanisterId: [] | [string];
    addedAt: bigint;
    symbol: string;
}): {
    decimals: number;
    ledgerCanisterId: string;
    indexCanisterId?: string;
    addedAt: bigint;
    symbol: string;
} {
    return {
        decimals: value.decimals,
        ledgerCanisterId: value.ledgerCanisterId,
        indexCanisterId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.indexCanisterId)),
        addedAt: value.addedAt,
        symbol: value.symbol
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n7(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomToken>): Array<CustomToken> {
    return value.map((x)=>from_candid_CustomToken_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
